### ISSUE TITLE
Add  Missing Visual Features to AzureAiServicesImageAnalysisTool

### ISSUE THREAD

**Issue by muniyi** [Sheepsta300/getting_started_openai_cookbook#83]
Based on the Research and Client feedback: [Image Analysis Missing Features](https://github.com/Sheepsta300/getting_started_openai_cookbook/blob/master/code_snippets/service_to_research.md#find-features-to-work-on)

**Comment by Sheepsta300** [comment]
After review from our client, the Service update is ready to be PR'd to the main LangChain repo for further review.
