### ISSUE TITLE
Enable Custom Visual Features in AzureAiServicesImageAnalysisTool

### ISSUE THREAD

**Issue by muniyi** [Sheepsta300/getting_started_openai_cookbook#84]
Based on the Research and Client feedback: [Image Analysis Missing Features](https://github.com/Sheepsta300/getting_started_openai_cookbook/blob/master/code_snippets/service_to_research.md#find-features-to-work-on), particularly from client suggestion.

>I think it would be nice, though, to allow the user to specify exactly what visual features they want and otherwise default to the ones originally chosen. Perhaps we can add the ability to pass in your own list of visual features?

**Comment by Sheepsta300** [comment]
After review from our client, the Service update is ready to be PR'd to the main LangChain repo for further review.
